name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - name: Lint Android
        run: ./gradlew lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew app:assemble

  assembleApks:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: create and checkout branch
        # push events already checked out the branch
        if: github.event_name == 'pull_request'
        env:
          BRANCH: ${{ github.head_ref }}
        run: git checkout -B "$BRANCH"

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"
          cache: 'gradle'

      - name: Build debug APK
        run: ./gradlew assembleFdroidDebug --stacktrace

      - name: Build release APK
        run: ./gradlew assembleFdroidRelease --stacktrace

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debugApk
          path: app/build/outputs/apk/fdroid/debug/*.apk

      - name: Upload relase APK
        uses: actions/upload-artifact@v3
        with:
          name: releaseApk
          path: app/build/outputs/apk/fdroid/release/*.apk
